import JSZip from "jszip";
import { Section } from "../models/section";

function base64ToBinary(b64string: string): Uint8Array {
	const binaryBuffer = Buffer.from(b64string, "base64");
	return new Uint8Array(binaryBuffer);
}

export async function Base64ZipToJSON(b64string: string): Promise<any> {
	const byteArray = base64ToBinary(b64string);

	const zip = new JSZip();
	const zipData = await zip.loadAsync(byteArray);

	//check that the data is contained in a file named courses
	if (Object.keys(zipData.files).length === 0 || Object.keys(zipData.files)[0] !== "courses/") {
		throw new Error("zipfile not in proper format, no folder named 'courses' found at top level");
	}

	/* the following code was partially generated by ChatGPT */
	const courseFilePromises = Object.keys(zipData.files)
		.filter((fileName) => fileName.startsWith("courses/"))
		.map(async (fileName) => {
			const file = zipData.file(fileName);
			if (file) {
				const fileContent = await file.async("string");
				const contentAsJSON = JSON.parse(fileContent);
				return { [fileName.replace("courses/", "")]: contentAsJSON };
			}
			return {};
		});

	const courseData = await Promise.all(courseFilePromises);
	/* end GPT code */

	//first course is empty object, since it reads the directory itself too as a course
	courseData.shift();

	return courseData;
}

/*
 * The JSON data parsed by the above Base64ZipToJSON function has the following form:
 *
 * {
 * 	[
 * 		"CPSC111": {
 * 			"result": [... array of sections]
 * 		},
 * 		"next course":{...}
 * 	]
 * }
 *
 * this function assumes this format
 * */
export function jsonToSections(jsonData: any): Section[] {
	const requiredFields = ["id", "Course", "Title", "Professor", "Subject", "Year", "Avg", "Pass", "Fail", "Audit"];
	const sections: Section[] = [];

	for (const course of jsonData) {
		const courseSections = course[Object.keys(course)[0]];
		for (const section of courseSections.result) {
			//assert that the required fields all exist
			requiredFields.forEach((field) => {
				if (!(field in section)) {
					throw new Error(`field ${field} not found in section data`);
				}
			});

			const sectionObj = new Section(
				section.id,
				section.Course,
				section.Title,
				section.Professor,
				section.Subject,
				section.Year,
				section.Avg,
				section.Pass,
				section.Fail,
				section.Audit
			);

			sections.push(sectionObj);
		}
	}

	return sections;
}
