import JSZip from "jszip";

function decodeBase64ZipToBlob(b64string: string): Blob {

	const binaryData = window.atob(b64string);

	const buffer = new ArrayBuffer(binaryData.length);
	const byteArray = new Uint8Array(buffer);
	for (let i = 0; i < binaryData.length; ++i) {
		byteArray[i] = binaryData.charCodeAt(i);
	}

	return new Blob([buffer]);
}

async function blobZipfileToJSON(blob: Blob): any {
	/* the following code was generated by ChatGPT */
	const zip = new JSZip();

	const zipData = await zip.loadAsync(blob);

	const courseFiles: JSZip.JSZipObject[] = [];
	zipData.forEach((_, file) => {
		if (file.name.startsWith("courses")) {
			courseFiles.push(file);
		}
	})

	const jsonPromises = courseFiles.map(async (file) => {
		const content = await file.async('string');
		return JSON.parse(content);
	})

	const jsonCourseData = await Promise.all(jsonPromises);

	return jsonCourseData;
}
